// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tiwyszgvxipbvcisrptb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpd3lzemd2eGlwYnZjaXNycHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTc1NDMsImV4cCI6MjA2NDQzMzU0M30.fdgfMJuAY5-C_M6lhQClSKQigo1hmBehPou3fWYFKfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);